pipeline {
    agent any
    environment {
        COMPOSE_PROJECT_NAME = "${env.JOB_NAME}-${env.BUILD_ID}"
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                
                sh 'set -x docker build -f ./services/posts/Dockerfile . -t microservices_posts-services'
            }
        }

        stage('Deploy'){
            steps {
                echo 'Deploy...'
                sh 'docker run '
            }
        }


        
    }
    
}