version: "2.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: "exit 0"
      interval: 10s
      timeout: s
      retries: 3 
  app:
    container_name: app
    restart: always
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8001:8001"
    links:
      - mongo
      - users-services
      - posts-services
  users-services:
    container_name: users-services
    restart: always
    build: 
      context: .
      dockerfile: ./services/users/Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8003:8003"
    links:
      - mongo
  posts-services:
    container_name: posts-services
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./services/posts/Dockerfile
    ports:
      - "8005:8005"
    links:
      - mongo  
